name: practica3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-99.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^4.15.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/img1.png
    - assets/imgs/img2.png
